-- Total count of rows in TICKET
SELECT COUNT(*) FROM TICKET;

-- Count of non-null TICKET_PRICE values
SELECT COUNT(TICKET_PRICE) FROM TICKET;

-- Maximum value of TICKET_PRICE
SELECT MAX(TICKET_PRICE) FROM TICKET;

-- Minimum value of TICKET_PRICE
SELECT MIN(TICKET_PRICE) FROM TICKET;

-- Sum of all TICKET_PRICE values
SELECT SUM(TICKET_PRICE) FROM TICKET;

-- Average of TICKET_PRICE values
SELECT AVG(TICKET_PRICE) FROM TICKET;
