-- Count of tickets grouped by PNR_NO
SELECT PNR_NO, COUNT(PNR_NO) AS "TOTAL BOOKED TICKET" FROM PAYMENT GROUP BY PNR_NO;

-- Sum of ticket prices grouped by PNR_NO
SELECT PNR_NO, SUM(TICKET_PRICE) AS "TOTAL INCOME FROM BOOKED TICKET" FROM TICKET GROUP BY PNR_NO;
