-- Count trains with a specific capacity
SELECT TRAIN_NO, TRAIN_NAME, CAPACITY, TRAIN_DESC, DESTINATION, ARRIVAL_TIME, COUNT(TRAIN_NO) AS "TOTAL TRAIN"
FROM TRAIN 
GROUP BY TRAIN_NO, TRAIN_NAME, CAPACITY, TRAIN_DESC, DESTINATION, ARRIVAL_TIME 
HAVING CAPACITY = '1008';

-- Count trains with a different specific capacity
SELECT TRAIN_NO, TRAIN_NAME, CAPACITY, TRAIN_DESC, DESTINATION, ARRIVAL_TIME, COUNT(TRAIN_NO) AS "TOTAL TRAIN"
FROM TRAIN 
GROUP BY TRAIN_NO, TRAIN_NAME, CAPACITY, TRAIN_DESC, DESTINATION, ARRIVAL_TIME 
HAVING CAPACITY = '1408';
